version: '3'
volumes:
    dados:
networks: 
    banco:
    web:
    fila:
services: 
    db:
        image: postgres:9.6
        environment: 
            - POSTGRES_PASSWORD="postgres"
        volumes:
            #Volume dos dados
            - dados:/var/lib/postgresql/data
            #Scripts
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks: 
            - banco
    frontend:
        image: nginx:1.13.0
        volumes:
            #Site
            - ./web:/usr/share/nginx/html/
            #Configuracao proxy reverso
            - ./nginx/default.conf:/etc/nginx/conf.d/
        ports: 
            - 80:80
        networks: 
            - web
        depends_on: 
            - app
    app:
        image: python:3.6
        volumes:
            #Aplicacao
            - ./app:/app
        working_dir: /app
        command: bash ./app.sh
        networks: 
            - banco
            - web
            - fila
        depends_on: 
            - db
            - queue
        environment: 
            - DB_NAME=email_postman
    queue:
        image: redis:3.2
        networks: 
            - fila
    worker:
        build: worker
        volumes: 
           #worker
            - ./worker:/worker
        working_dir: /worker
        command: worker.py
        networks: 
            - fila
        depends_on: 
            - queue